from Produtos import *
from tkinter import *

class Sistema:
    def __init__(self, master=None): # Tela Principal
        root.title('Sistema de Estoque')
        root.geometry('1300x690+0+0')
        menu = Menu(root)
        root.config(menu=menu)
        filemenu = Menu(menu)
        menu.add_cascade(label='Produtos', menu=filemenu)
        filemenu.add_command(label='Cadastrar Novo', command=self.cadastrar)
        filemenu.add_command(label='Alterar Produto', command=self.atualizar)
        filemenu.add_command(label='Saida de Produtos',)
        filemenu.add_command(label='Entrada de Produtos',)
        filemenu.add_separator()
        filemenu.add_command(label='Sair', command=root.quit)

    def cadastrar(self): # Tela de Cadastro
        self.janela = Tk()
        self.janela.title('Cadastrar')
        self.janela.geometry('500x250+0+50')
        self.nome = Label(self.janela, text='Nome: ')
        self.nomeProd = Entry(self.janela)
        self.codigo = Label(self.janela, text='Código: ')
        self.codigoProd = Entry(self.janela)
        self.qtdNovo = Label(self.janela, text='Quantidade Comprada: ')
        self.qtdNovoProd = Entry(self.janela)
        self.qtdMinima = Label(self.janela, text='Quantidade Mínima no estoque: ')
        self.qtdMinimaProd = Entry(self.janela)
        self.cadastrar = Button(self.janela, text='Cadastrar', command=self.inserirProduto)
        self.voltar = Button(self.janela, text='<< Voltar', command=self.janela.destroy)
        self.status = Label(self.janela, text='')
        self.nome.grid(row=0, column=0, pady=10)
        self.nomeProd.grid(row=0, column=1)
        self.codigo.grid(row=1, column=0, pady=10)
        self.codigoProd.grid(row=1, column=1)
        self.qtdNovo.grid(row=2, column=0, pady=10)
        self.qtdNovoProd.grid(row=2, column=1)
        self.qtdMinima.grid(row=3, column=0, pady=10)
        self.qtdMinimaProd.grid(row=3, column=1)
        self.cadastrar.grid(row=4, column=1, pady=10)
        self.voltar.grid(row=4, column=0, pady=10)
        self.status.grid(row=5, column=0, columnspan=2, pady=10)

    def atualizar(self): # Tela de alteração de produto
        self.janela = Tk()
        self.janela.title('Atualizar Produto')
        self.janela.geometry('500x300+0+50')
        self.codigo = Label(self.janela, text='Código: ')
        self.codigoProd = Entry(self.janela)
        self.buscar = Button(self.janela, text='Buscar', command=self.buscarProduto)
        self.nome = Label(self.janela, text='Nome: ')
        self.nomeProd = Entry(self.janela)
        self.qtdNovo = Label(self.janela, text='Quantidade Comprada: ')
        self.qtdNovoProd = Entry(self.janela)
        self.qtdMinima = Label(self.janela, text='Quantidade Mínima no estoque: ')
        self.qtdMinimaProd = Entry(self.janela)
        self.cadastrar = Button(self.janela, text='Salvar Produto', command=self.alterarProduto)
        self.voltar = Button(self.janela, text='<< Voltar', command=self.janela.destroy)
        self.excluir = Button(self.janela, text='Excluir Produto', command=self.excluirProduto)
        self.status = Label(self.janela, text='')
        self.codigo.grid(row=0, column=0, pady=10)
        self.codigoProd.grid(row=0, column=1)
        self.buscar.grid(row=1, column=1, pady=10)
        self.nome.grid(row=2, column=0, pady=10)
        self.nomeProd.grid(row=2, column=1, pady=10)
        self.qtdNovo.grid(row=3, column=0, pady=10)
        self.qtdNovoProd.grid(row=3, column=1)
        self.qtdMinima.grid(row=4, column=0, pady=10)
        self.qtdMinimaProd.grid(row=4, column=1)
        self.cadastrar.grid(row=5, column=1, pady=10)
        self.voltar.grid(row=5, column=0, pady=10)
        self.excluir.grid(row=5, column=2, pady=10)
        self.status.grid(row=6, column=0, columnspan=2, pady=10)

    def inserirProduto(self): # função de inserção
        prod = Produtos()
        prod.nome = self.nomeProd.get()
        prod.qtd = self.qtdNovoProd.get()
        prod.qtdMinima = self.qtdMinimaProd.get()
        prod.codigo = self.codigoProd.get()
        self.status['text'] = prod.insertProd()
        self.nomeProd.delete(0, END)
        self.qtdNovoProd.delete(0, END)
        self.qtdMinimaProd.delete(0, END)
        self.codigoProd.delete(0, END)

    def buscarProduto(self): # função de busca
        prod = Produtos()
        codigo = self.codigoProd.get()
        self.status['text'] = prod.selectProd(codigo)
        self.nomeProd.delete(0, END)
        self.nomeProd.insert(INSERT, prod.nome)
        self.qtdNovoProd.delete(0, END)
        self.qtdNovoProd.insert(INSERT, prod.qtd)
        self.qtdMinimaProd.delete(0, END)
        self.qtdMinimaProd.insert(INSERT, prod.qtdMinima)

    def excluirProduto(self):
        prod = Produtos()
        prod.codigo = self.codigoProd.get()
        self.status['text'] = prod.deleteProd()
        self.nomeProd.delete(0, END)
        self.qtdNovoProd.delete(0, END)
        self.qtdMinimaProd.delete(0, END)

    def alterarProduto(self):
        prod = Produtos()
        prod.codigo = self.codigoProd.get()
        prod.nome = self.nomeProd.get()
        prod.qtd = self.qtdNovoProd.get()
        prod.qtdMinima = self.qtdMinimaProd.get()
        self.status['text'] = prod.updateProd()
        self.noeProd.delete(0, END)
        self.qtdNovoProd.delete(0, END)
        self.qtdMinimaProd.delete(0, END)

root = Tk()
Sistema(root)
root.mainloop()
